---
title: "Analyse_finale"
output: html_document
date: "2022-11-27"
---


```{r recup, echo=TRUE}
load('../Donnees/Dataset_total.Rdata')
head(dataset_total)
```

# Création variable reste à charge

```{r}
dataset_total$RAC_2018 <- dataset_total$Mnt_dep_2018 - dataset_total$Remb_rc_2018 - dataset_total$Remb_ro_2018

dataset_total$RAC_2019 <- dataset_total$Mnt_dep_2019 - dataset_total$Remb_rc_2019 - dataset_total$Remb_ro_2019

dataset_total$RAC_2020 <- dataset_total$Mnt_dep_2020 - dataset_total$Remb_rc_2020- dataset_total$Remb_ro_2020

dataset_total$RAC_2021<- dataset_total$Mnt_dep_2021 - dataset_total$Remb_rc_2021 - dataset_total$Remb_ro_2021

dataset_total$RAC_2022<- dataset_total$Mnt_dep_2022 - dataset_total$Remb_rc_2022 - dataset_total$Remb_ro_2022


 
```


# Création du P/C 


```{r}
dataset_total$PC_2018 <- ifelse(dataset_total$Mnt_2018==0,0,dataset_total$Remb_ro_2018 /dataset_total$Mnt_2018)


dataset_total$PC_2019 <- ifelse(dataset_total$Mnt_2019==0,0,dataset_total$Remb_ro_2019 /dataset_total$Mnt_2019)

dataset_total$PC_2020 <- ifelse( dataset_total$Mnt_2020==0,0,dataset_total$Remb_ro_2020 /dataset_total$Mnt_2020)

dataset_total$PC_2021 <- ifelse(dataset_total$Mnt_2021==0,0,dataset_total$Remb_ro_2021 /dataset_total$Mnt_2021)


dataset_total$PC_2022 <- ifelse(dataset_total$Mnt_2022==0,0,dataset_total$Remb_ro_2022 /dataset_total$Mnt_2022)
```




# Variation de P/C en %

```{r}
dataset_total$VAR_PC2221 <-  ifelse(dataset_total$PC_2021==0,0,(dataset_total$PC_2022 /dataset_total$PC_2021 -1) *100)

dataset_total$VAR_PC2120 <-  ifelse(dataset_total$PC_2020==0,0, (dataset_total$PC_2021 /dataset_total$PC_2020 -1) *100)

dataset_total$VAR_PC2019 <-  ifelse(dataset_total$PC_2019==0,0,(dataset_total$PC_2020 /dataset_total$PC_2019 -1)*100)

dataset_total$Var_PC1918 <-  ifelse(dataset_total$PC_2018==0,0,(dataset_total$PC_2019 /dataset_total$PC_2018 -1) *100)
```




# Prestations PP


```{r}
dataset_total$Prest_PP_2018 <- ifelse( dataset_total$Nb_pers_2018==0,0,dataset_total$Remb_ro_2018 / dataset_total$Nb_pers_2018)
dataset_total$Prest_PP_2019 <- ifelse( dataset_total$Nb_pers_2019==0,0,dataset_total$Remb_ro_2019 / dataset_total$Nb_pers_2019)
dataset_total$Prest_PP_2020 <- ifelse( dataset_total$Nb_pers_2020==0,0,dataset_total$Remb_ro_2020 / dataset_total$Nb_pers_2020)
dataset_total$Prest_PP_2021 <- ifelse( dataset_total$Nb_pers_2021==0,0,dataset_total$Remb_ro_2021 / dataset_total$Nb_pers_2021)
dataset_total$Prest_PP_2022 <- ifelse( dataset_total$Nb_pers_2022==0,0,dataset_total$Remb_ro_2022 / dataset_total$Nb_pers_2022)
```


# Variation de prestations par PP 

```{r}
dataset_total$VAR_Pr2221 <-  ifelse(dataset_total$Prest_PP_2021==0,0, (dataset_total$Prest_PP_2022 /dataset_total$Prest_PP_2021 -1) *100)

dataset_total$VAR_Pr2120 <-  ifelse(dataset_total$Prest_PP_2020==0,0, (dataset_total$Prest_PP_2021 /dataset_total$Prest_PP_2020 -1) *100)

dataset_total$VAR_Pr2019 <-  ifelse(dataset_total$Prest_PP_2019==0,0, (dataset_total$Prest_PP_2020 /dataset_total$Prest_PP_2019 -1)*100)

dataset_total$Var_Pr1918 <-  ifelse(dataset_total$Prest_PP_2018==0,0, (dataset_total$Prest_PP_2019 /dataset_total$Prest_PP_2018  -1)*100)

```

# Cotisations PP


```{r}
dataset_total$Cot_PP_2018 <- ifelse( dataset_total$Nb_pers_2018==0,0,dataset_total$Mnt_2018/ dataset_total$Nb_pers_2018)
dataset_total$Cot_PP_2019 <- ifelse( dataset_total$Nb_pers_2019==0,0,dataset_total$Mnt_2019 / dataset_total$Nb_pers_2019)
dataset_total$Cot_PP_2020 <- ifelse( dataset_total$Nb_pers_2020==0,0,dataset_total$Mnt_2020 / dataset_total$Nb_pers_2020)
dataset_total$Cot_PP_2021 <- ifelse( dataset_total$Nb_pers_2021==0,0,dataset_total$Mnt_2021 / dataset_total$Nb_pers_2021)
dataset_total$Cot_PP_2022 <- ifelse( dataset_total$Nb_pers_2022==0,0,dataset_total$Mnt_2022 / dataset_total$Nb_pers_2022)
```


```{r}
dataset_total$VAR_Cot2221 <-  ifelse(dataset_total$Cot_PP_2021,0, (dataset_total$Cot_PP_2022 /dataset_total$Cot_PP_2021 -1)*100)

dataset_total$VAR_Cot2120 <-  ifelse(dataset_total$Cot_PP_2020==0,0,(dataset_total$Cot_PP_2021 /dataset_total$Cot_PP_2020 -1)*100)

dataset_total$VAR_Cot2019 <-  ifelse(dataset_total$Cot_PP_2019==0,0,(dataset_total$Cot_PP_2020 /dataset_total$Cot_PP_2019 -1) *100)

dataset_total$Var_Cot1918 <-  ifelse(dataset_total$Cot_PP_2018==0,0,(dataset_total$Cot_PP_2019 /dataset_total$Cot_PP_2018 -1)*100)

```

# Save


```{r save}
save(dataset_total, file='../Donnees/Dataset_total.Rdata')
```


