---
title: "Dataset_par_annee"
author: "Manon Santrisse"
date: '2022-12-01'
output: html_document
---

# Recup datset total

```{r recup eff, echo=TRUE}
load('../Donnees/Dataset_total.Rdata')
head(dataset_total)
```


# Division du jeu de données par année

## 2018

```{r 2018, echo=TRUE}
dataset_2018=dataset_total[,c(1:23,97,98,103,104:107,124:128,149,154,162,163,171,172,180)]
head(dataset_2018)
```


```{r save}
save(dataset_2018, file='../Donnees/Donnees_annnee/Dataset_2018.Rdata')
```


##2019

```{r 2019, echo=TRUE}
dataset_2019=dataset_total[,c(1:6,24:40,97,99,103,108:111,129:133,150,155,161,162,164,170,171,173,179,180)]
head(dataset_2019)
```


```{r save}
save(dataset_2019, file='../Donnees/Donnees_annnee/Dataset_2019.Rdata')
```

##2020

```{r 2020, echo=TRUE}
dataset_2020=dataset_total[,c(1:6,41:58,97,101,103,112:115,134:138,151,156,160,161,169,170,174,178,179)]
head(dataset_2020)
```


```{r save}
save(dataset_2020, file='../Donnees/Donnees_annnee/Dataset_2020.Rdata')
```

##2021


```{r 2021, echo=TRUE}
dataset_2021=dataset_total[,c(1:6,59:76,97,101,103,116:119,139:143,152,157,159,160,166,168,169,175,177,178)]
head(dataset_2021)
```


```{r save}
save(dataset_2021, file='../Donnees/Donnees_annnee/Dataset_2021.Rdata')
```


##2022
```{r 2022, echo=TRUE}
dataset_2022=dataset_total[,c(1:6,77:96,97,102,103,120:123,144:148,153,158,159,167,168,176,177)]
head(dataset_2022)
```


```{r save}
save(dataset_2022, file='../Donnees/Donnees_annnee/Dataset_2022.Rdata')
```














































