---
title: "Merge du jeu de donnees"
author: "Manon Santrisse"
date: '2022-11-26'
output: html_document
---

```{r library, include=FALSE}
library(dplyr)
library(ggplot2)
library(corrplot)
library(readxl)
library(FactoMineR)
library(factoextra)
library(cowplot)
library("NbClust")
library(missForest)
library(writexl)
library("scales")
library(readr)
library(lubridate)
library(data.table)
```


# Récupération des jeux de données

## jeu Effectifs_final+.Rdata
```{r recup eff, echo=TRUE}
load('../Donnees/Effectifs/Effectif_final_freq.Rdata')
head(tab_eff_freq)
```
 Retrait variable Base
```{r}
tab_eff_freq=tab_eff_freq[,-c(9,26,43,61,79)]
```
 
## jeu Cotisation.Rdata

```{r}
load(file = "../Donnees/Cotisations/Cotisations_modif.Rdata")
```

```{r recup coti, echo=TRUE}
# load('../Donnees/Cotisations/cotisations.Rdata')
# tab_cotisations=tab
# rm(tab)
# head(tab_cotisations)
```

### Formatage cotisations

```{r}
# tab_cotisations$Lien_E=as.factor(tab_cotisations$Lien_E)
# 
# tab_cotisations$Max_regroup1 <- sapply(strsplit(tab_cotisations$Max_regroup1,"_"),function(x){return (x[2])})
# tab_cotisations$Max_regroup1=as.factor(tab_cotisations$Max_regroup1)

# 
# tab_cotisations$Max_regroup2 <- sapply(strsplit(tab_cotisations$Max_regroup2,"_"),function(x){return (x[1])})
# tab_cotisations$Max_regroup2=as.factor(tab_cotisations$Max_regroup2)
# 
# tab_cotisations$Max_regroup3 <- sapply(strsplit(tab_cotisations$Max_regroup3,"_"),function(x){return (x[1])})
# tab_cotisations$Max_regroup3=as.factor(tab_cotisations$Max_regroup3)
# 
# colnames(tab_cotisations)[2:5]=c("Regroup1","Regroup4","Regroup2","Regroup3")
# 
# head(tab_cotisations)
```



```{r save}
# save(tab_cotisations, file='../Donnees/Cotisations/Cotisations_modif.Rdata')
```


## jeu Prestations_final.Rdata

```{r}
load(file = "../Donnees/Prestations/prestations2.Rdata")
tab_prestations=tab
```

```{r recup presta, echo=TRUE}
# tab_prestations=read.table('../Donnees/Prestations/Prestations_final.csv',sep=";")
# colnames(tab_prestations)=tab_prestations[1,]
# tab_prestations=tab_prestations[-1,]
# colnames(tab_prestations)[5:8]=c("Regroup1","Regroup4","Regroup2","Regroup3")
# head(tab_prestations)
```

### Formatage

```{r}
# tab_prestations$Lien_E=as.factor(tab_prestations$Lien_E)
# 
# tab_prestations$Actifs=as.numeric(tab_prestations$Actifs)
# tab_prestations$Non_actifs=as.numeric(tab_prestations$Non_actifs)
# tab_prestations$Portabilite=as.numeric(tab_prestations$Portabilite)
# 
# tab_prestations$Max_regroup1 <- sapply(strsplit(tab_prestations$Regroup1,"_"),function(x){return (x[2])})
# 
# tab_prestations$Max_regroup2 <- sapply(strsplit(tab_prestations$Regroup2,"_"),function(x){return (x[1])})
# 
# tab_prestations$Max_regroup3 <- sapply(strsplit(tab_prestations$Regroup3,"_"),function(x){return (x[1])})
# 
# tab_prestations$Max_regroup1=as.factor(tab_prestations$Regroup1)
# tab_prestations$Max_regroup4=as.factor(tab_prestations$Regroup4)
# tab_prestations$Max_regroup2=as.factor(tab_prestations$Regroup2)
# tab_prestations$Max_regroup3=as.factor(tab_prestations$Regroup3)
# 
# tab_prestations$Base=as.numeric(tab_prestations$Base)
# tab_prestations$Option=as.numeric(tab_prestations$Option)
# 
# tab_prestations$Mnt_dep_2018=as.numeric(tab_prestations$Mnt_dep_2018)
# tab_prestations$Remb_rc_2018=as.numeric(tab_prestations$Remb_rc_2018)
# tab_prestations$Remb_ro_2018=as.numeric(tab_prestations$Remb_ro_2018)
# tab_prestations$Qte_acte_2018=as.numeric(tab_prestations$Qte_acte_2018)
# 
# tab_prestations$Mnt_dep_2019=as.numeric(tab_prestations$Mnt_dep_2019)
# tab_prestations$Remb_rc_2019=as.numeric(tab_prestations$Remb_rc_2019)
# tab_prestations$Remb_ro_2019=as.numeric(tab_prestations$Remb_ro_2019)
# tab_prestations$Qte_acte_2019=as.numeric(tab_prestations$Qte_acte_2019)
# 
# tab_prestations$Mnt_dep_2020=as.numeric(tab_prestations$Mnt_dep_2020)
# tab_prestations$Remb_rc_2020=as.numeric(tab_prestations$Remb_rc_2020)
# tab_prestations$Remb_ro_2020=as.numeric(tab_prestations$Remb_ro_2020)
# tab_prestations$Qte_acte_2020=as.numeric(tab_prestations$Qte_acte_2020)
# 
# tab_prestations$Mnt_dep_2021=as.numeric(tab_prestations$Mnt_dep_2021)
# tab_prestations$Remb_rc_2021=as.numeric(tab_prestations$Remb_rc_2021)
# tab_prestations$Remb_ro_2021=as.numeric(tab_prestations$Remb_ro_2021)
# tab_prestations$Qte_acte_2021=as.numeric(tab_prestations$Qte_acte_2021)
# 
# tab_prestations$Mnt_dep_2022=as.numeric(tab_prestations$Mnt_dep_2022)
# tab_prestations$Remb_rc_2022=as.numeric(tab_prestations$Remb_rc_2022)
# tab_prestations$Remb_ro_2022=as.numeric(tab_prestations$Remb_ro_2022)
# tab_prestations$Qte_acte_2022=as.numeric(tab_prestations$Qte_acte_2022)
# 
# tab_prestations$Dentaire_2018=as.numeric(tab_prestations$Dentaire_2018)
# tab_prestations$Maladie_2018=as.numeric(tab_prestations$Maladie_2018)
# tab_prestations$Vie_2018=as.numeric(tab_prestations$Vie_2018)
# tab_prestations$Hospitalisation_2018=as.numeric(tab_prestations$Hospitalisation_2018)
# tab_prestations$Optique_2018=as.numeric(tab_prestations$Optique_2018)
# 
# tab_prestations$Dentaire_2019=as.numeric(tab_prestations$Dentaire_2019)
# tab_prestations$Maladie_2019=as.numeric(tab_prestations$Maladie_2019)
# tab_prestations$Vie_2019=as.numeric(tab_prestations$Vie_2019)
# tab_prestations$Hospitalisation_2019=as.numeric(tab_prestations$Hospitalisation_2019)
# tab_prestations$Optique_2019=as.numeric(tab_prestations$Optique_2019)
# 
# tab_prestations$Dentaire_2020=as.numeric(tab_prestations$Dentaire_2020)
# tab_prestations$Maladie_2020=as.numeric(tab_prestations$Maladie_2020)
# tab_prestations$Vie_2020=as.numeric(tab_prestations$Vie_2020)
# tab_prestations$Hospitalisation_2020=as.numeric(tab_prestations$Hospitalisation_2020)
# tab_prestations$Optique_2020=as.numeric(tab_prestations$Optique_2020)
# 
# tab_prestations$Dentaire_2021=as.numeric(tab_prestations$Dentaire_2021)
# tab_prestations$Maladie_2021=as.numeric(tab_prestations$Maladie_2021)
# tab_prestations$Vie_2021=as.numeric(tab_prestations$Vie_2021)
# tab_prestations$Hospitalisation_2021=as.numeric(tab_prestations$Hospitalisation_2021)
# tab_prestations$Optique_2021=as.numeric(tab_prestations$Optique_2021)
# 
# tab_prestations$Dentaire_2022=as.numeric(tab_prestations$Dentaire_2022)
# tab_prestations$Maladie_2022=as.numeric(tab_prestations$Maladie_2022)
# tab_prestations$Vie_2022=as.numeric(tab_prestations$Vie_2022)
# tab_prestations$Hospitalisation_2022=as.numeric(tab_prestations$Hospitalisation_2022)
# tab_prestations$Optique_2022=as.numeric(tab_prestations$Optique_2022)
# 
# 
# head(tab_prestations)
```


```{r save}
# save(tab_prestations, file='../Donnees/Prestations/Prestations.Rdata')
```

# Merge les jeux de données
Retrait de code ape et départment dans effectifs.
Retrait des taxes dans cotisations .
```{r merge}
dataset_total <- merge(tab_eff_freq[,-c(2,3)], tab_cotisations[,c(1,6,12:25)], by = 'Lien_E')
```

```{r merge}
dataset_total <- merge(dataset_total, tab_prestations[,c(1,11:50)], by = 'Lien_E')
```

# Save


```{r save}
save(dataset_total, file='../Donnees/Dataset_total.Rdata')
```

