---
title: "Effectifs_freeze"
author: "Manon Santrisse"
date: "13/10/2022"
output: html_document
---


```{r}
library(dplyr)
library(ggplot2)
library(corrplot)
library(readxl)
library(FactoMineR)
library(factoextra)
library(cowplot)
library("NbClust")
library(missForest)
library(writexl)
```

# Récupération du jeu Effectifs.xlsx
```{r}
data=read_excel('./Donnees/Effectifs_freeze.xlsx')
data
```

# Simplifier les valeurs

```{r}
data$`Num Ctr Coll Anonyme` <- sapply(strsplit(data$`Num Ctr Coll Anonyme`,"-"),function(x){return (x[1])})
data$`Lib Entreprise Anonyme`<- sapply(strsplit(data$`Lib Entreprise Anonyme`,"-"),function(x){return (x[1])})
data$`Produit Anonyme`<- sapply(strsplit(data$`Produit Anonyme`,"-"),function(x){return (x[1])})
data$`Num Personne Anonyme`<- sapply(strsplit(data$`Num Personne Anonyme`,"-"),function(x){return (x[1])})
data$`Num Ctr Indiv Anonyme`<- sapply(strsplit(data$`Num Ctr Indiv Anonyme`,"-"),function(x){return (x[1])})
data$`Lien entreprise Anonyme`<- sapply(strsplit(data$`Lien entreprise Anonyme`,"-"),function(x){return (x[1])})
data
```



# Factorisaion de certaines variables

```{r}
data$`Num Ctr Coll Anonyme`<-factor(data$`Num Ctr Coll Anonyme`)
data$`Lib Entreprise Anonyme`<-factor(data$`Lib Entreprise Anonyme`)
data$`Code Grp Assures`<-factor(data$`Code Grp Assures`)
data$`Condition Vente`<-factor(data$`Condition Vente`)
data$`Produit Anonyme`<-factor(data$`Produit Anonyme`)
data$`Code Ape`<-factor(data$`Code Ape`)
data$Departement<-factor(data$Departement)
data$REGROUP_PROD_1<-factor(data$REGROUP_PROD_1)
data$REGROUP_PROD_2<-factor(data$REGROUP_PROD_2)
data$REGROUP_PROD_3<-factor(data$REGROUP_PROD_3)
data$`REGROUP_PROD_4 Anonyme`<-factor(data$`REGROUP_PROD_4 Anonyme`)
data$REGROUP_PROD_5<-factor(data$REGROUP_PROD_5)
data$`Num Ctr Indiv Anonyme`<- factor(data$`Num Ctr Indiv Anonyme`)
data$`Type Assure`<-factor(data$`Type Assure`)
data$Sexe<-factor(data$Sexe)
data$`R/NR`<-factor(data$`R/NR`)
data$`Lien entreprise Anonyme`<-factor(data$`Lien entreprise Anonyme`)
data$`Numéro contrat coll Grands Comptes`<-factor(data$`Numéro contrat coll Grands Comptes`)	
data$`Renégo 2020`<-factor(data$`Renégo 2020`)
data$`Renégo 2021`<-factor(data$`Renégo 2021`)
data$`Renégo 2022`<-factor(data$`Renégo 2022`)


data

```


```{r}
#levels(data$`REGROUP_PROD_1`)
#levels(data$`REGROUP_PROD_2`)
#levels(data$`REGROUP_PROD_3`)
#levels(data$`REGROUP_PROD_4 Anonyme`)
#levels(data$`REGROUP_PROD_5`)
```
Il y a une seule catégorie pour regroup_prod 2 et 3 donc on ne va pas les étudier.

```{r}
data=data[,-c(11,12)]
head(data)
```
  
# Gestion des Dates
```{r}
data=transform(data,`Date Effet Adhesion Contrat Coll` =as.character(`Date Effet Adhesion Contrat Coll`),`Date Effet Radiation Contrat Coll` =as.character(`Date Effet Radiation Contrat Coll`),`Date Effet Adhesion Num Personne`=as.character(`Date Effet Adhesion Num Personne`), `Date Effet Radiation Num Personne`=as.character(`Date Effet Radiation Num Personne`), `Date Naissance`=as.character(`Date Naissance`))

head(data)
```

```{r}
data$Date.Effet.Adhesion.Contrat.Coll<-as.Date(data$Date.Effet.Adhesion.Contrat.Coll, format = "%Y%m%d")
data$Date.Effet.Radiation.Contrat.Coll <-as.Date(data$Date.Effet.Radiation.Contrat.Coll, format = "%Y%m%d")
data$Date.Effet.Adhesion.Num.Personne <- as.Date(data$Date.Effet.Adhesion.Num.Personne,  format = "%Y-%m-%d")
data$Date.Effet.Radiation.Num.Personne <-as.Date(data$Date.Effet.Radiation.Num.Personne, format = "%Y%m%d")
data$Date.Naissance <- as.Date(data$Date.Naissance,  format = "%Y-%m-%d")
head(data)
```

# Summary

```{r}
summary(data)
```



# Racourcis noms variables
```{r}
Num_E=data$Num.Ctr.Coll.Anonyme
Nom_E=data$Lib.Entreprise.Anonyme
Gp_assures=data$Code.Grp.Assures
cond_vente=data$Condition.Vente
Prod=data$Produit.Anonyme
Date_adh_coll=data$Date.Effet.Adhesion.Contrat.Coll
Date_rad_coll=data$Date.Effet.Radiation.Contrat.Coll
Secteur=data$Code.Ape
REGROUP_PROD_4=data$REGROUP_PROD_4.Anonyme
Num_P=data$Num.Personne.Anonyme
Num_Fam=data$Num.Ctr.Indiv.Anonyme
Date_adh_pers=data$Date.Effet.Adhesion.Num.Personne
Date_rad_pers=data$Date.Effet.Radiation.Num.Personne
Type=data$Type.Assure
Date_Naissance=data$Date.Naissance
Lien=data$Lien.entreprise.Anonyme
Index2018=data$Indexation.2018
Index2019=data$Indexation.2019
Index2020=data$Indexation.2020
Index2021=data$Indexation.2021
Index2022=data$Indexation.2022
Index2023=data$Indexation.2023
Nego2020=data$Renégo.2020
Nego2021=data$Renégo.2021
Nego2022=data$Renégo.2022

```


# Focus entreprise 1 avant de faire une boucle

```{r}
E1=subset(data,Num_E=='1')
summary(E1)
```



