



```{r library, include=FALSE}
library(dplyr)
library(ggplot2)
library(corrplot)
library(readxl)
library(FactoMineR)
library(factoextra)
library(cowplot)
library("NbClust")
library(writexl)
library("scales")
library(readr)
library(lubridate)
library(data.table)
```

# Récupération du jeu Effectifs_freeze.Rdata
```{r recup, echo=TRUE}
load('../../Donnees/Cotisations/cotisations.Rdata')
```

```{r}
nb_tab <- nrow(tab)
```


# Code groupe assurés selon les cotisations

```{r}
df1 = stack(tab[,c(9,10,11)])
df1= subset(df1,values!=0)
df1=aggregate(df1[,1],list(df1[,2]),sum)
df1$percent=paste(as.character(round(df1$x/sum(df1$x)*100,2)),"%")
colnames(df1)[1] <- c("Code_grp")
ggplot(df1, aes(x="", y=x, fill=Code_grp)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
  geom_text(aes(label = percent),
            position = position_stack(vjust = 0.8)) +
   ggtitle("Code groupe assurés") +theme_void()
```



# Base et option sellon les cotisations

```{r}
#for (i in 1:nb_lien){
  df1 = stack(tab[,c(7,8)])
  df1= subset(df1,values!=0)
  df1=aggregate(df1[,1],list(df1[,2]),sum)
  df1$percent=paste(as.character(round(df1$x/sum(df1$x)*100,2)),"%")
  print(ggplot(df1, aes(x="", y=x,fill=Group.1)) +
    geom_bar(stat="identity", width=1) +
    coord_polar("y", start=0)+
      theme_void()+
    geom_text(aes(label = percent),
            position = position_stack(vjust = 0.8)) +
    ggtitle("Base et option "))
#}
```





# Regroup1

```{r}
t=aggregate(tab[,2],list(tab[,2]),length)
colnames(t)[1]<-c("Regroup1")
t= subset(t,x!=0)
t$percent=paste(as.character(round(t$x/sum(t$x)*100,2)),"%")
ggplot(t, aes(x="", y=x, fill=Regroup1)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
  theme_void()+
  geom_text(aes(label = percent),
            position = position_stack(vjust = 0.4)) 
```






```{r}
par(mfrow=c(1,1))
hist(tab$Mnt_total)
hist(tab$Taxe_totale)
```

```{r}
hist(as.numeric(tab$Max_prod_mnt),main = "Montant de cotisations")
hist(as.numeric(tab$Max_prod_taxe) , main =" Montant des taxes")

```

```{r}
hist(as.numeric(tab$Max_prod_mnt),main = "Montant de cotisations",xlim=c(0,quantile(as.numeric(tab$Max_prod_mnt),0.9)))
hist(as.numeric(tab$Max_prod_taxe) , main =" Montant des taxes",xlim=c(0,quantile(as.numeric(tab$Max_prod_mnt),0.9)))
```





```{r}
boxplot(tab[,c(13,15,16,18,21)],ylim=c(0,100000))
boxplot(tab[,c(13,15,16,18,21)],ylim=c(0,quantile(tab$Mnt_2022,0.9)))
```


```{r}
boxplot(tab[,c(12,14,17,19,20)])
boxplot((tab[,c(12,14,17,19,20)]),ylim=c(0,quantile(tab$Taxe_2022,0.9)))
boxplot(tab[,c(12,14,17,19,20)],ylim = c(0,10000))
```

